#!/usr/bin/env python3
"""Bake .cl sources into a C++ header as self-contained strings.

An OpenCL runtime compiler has no filesystem to #include from: it is handed
one block of source text. Our kernels do include a first-party header --
<semper/kernels/canonical_math.h>, which is the whole point of the design,
since the same text must compile into both the host library and the device
program -- so the include has to be resolved here, at build time.

This is a RECURSIVE TEXTUAL EXPANDER, not a concatenation, and it must not
deduplicate. canonical_math.h includes canonical_reductions.inc *twice*, once
per OpenCL address space (unsuffixed for private, _g for __global), because
OpenCL C 1.2 has no generic address space. Each occurrence has to expand
separately or the _g variants never exist and every kernel taking a __global
pointer fails to build.

Only first-party includes are resolved. Anything not found on the search path
is left in place, so a genuine mistake surfaces as a device compiler error
naming the missing header rather than being silently dropped.
"""

import argparse
import pathlib
import re
import sys

INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*[<"]([^>"]+)[>"][ \t]*$')
MAX_DEPTH = 32  # cycle guard; real depth here is 2


def expand(path: pathlib.Path, include_dirs, depth=0, stack=None):
    if depth > MAX_DEPTH:
        raise RuntimeError(f"include depth exceeded at {path} (cycle?): {stack}")
    stack = (stack or []) + [str(path)]
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = INCLUDE_RE.match(line)
        if not m:
            out.append(line)
            continue
        name = m.group(1)
        resolved = None
        # Sibling of the including file first, then the search path -- the
        # same order a C preprocessor uses for quoted includes.
        for base in [path.parent] + list(include_dirs):
            cand = pathlib.Path(base) / name
            if cand.is_file():
                resolved = cand
                break
        if resolved is None:
            # Not ours. Leave it for the device compiler to complain about.
            out.append(line)
            continue
        out.append(f"/* >>> expanded: {name} */")
        out.extend(expand(resolved, include_dirs, depth + 1, stack))
        out.append(f"/* <<< end: {name} */")
    return out


def ident(p: pathlib.Path) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", p.stem).upper()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", required=True)
    ap.add_argument("--include-dir", action="append", default=[])
    ap.add_argument("kernels", nargs="+")
    a = ap.parse_args()

    chunks = [
        "// Generated by scripts/embed_cl_kernels.py -- do not edit.",
        "// Each string is one self-contained OpenCL translation unit with all",
        "// first-party includes already expanded.",
        "#ifndef SEMPER_GPU_EMBEDDED_KERNELS_HPP",
        "#define SEMPER_GPU_EMBEDDED_KERNELS_HPP",
        "",
        "namespace Semper {",
        "namespace gpu {",
        "namespace kernels {",
        "",
    ]

    for k in a.kernels:
        p = pathlib.Path(k)
        if not p.is_file():
            print(f"error: kernel not found: {p}", file=sys.stderr)
            return 1
        body = "\n".join(expand(p, a.include_dir))
        # Raw literal: the delimiter must not appear in the source. Kernels are
        # ours, so assert rather than invent an escaping scheme.
        if ')CLSRC"' in body:
            print(f"error: {p} contains the raw-string delimiter", file=sys.stderr)
            return 1
        chunks.append(f"// ---- {p.name} ----")
        chunks.append(f'inline constexpr char {ident(p)}[] = R"CLSRC(')
        chunks.append(body)
        chunks.append(')CLSRC";')
        chunks.append("")

    chunks += ["} // namespace kernels", "} // namespace gpu", "} // namespace Semper",
               "", "#endif", ""]

    out = pathlib.Path(a.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(chunks)
    # Avoid touching the file when unchanged, so CMake does not rebuild the world.
    if not out.is_file() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
